### ISSUE TITLE
UnsatisfiedLinkError: No implementation found for void demo.tensorflow.org.customvision_sample.env.ImageUtils.convertYUV420SPToARGB8888

### ISSUE THREAD

**Issue by alexnik0888** [Azure-Samples/cognitive-services-android-customvision-sample#1]
### I've tried to run your example but unfortunately got this error at start
```
java.lang.UnsatisfiedLinkError: No implementation found for void demo.tensorflow.org.customvision_sample.env.ImageUtils.convertYUV420SPToARGB8888(byte[], int[], int, int, boolean) (tried Java_demo_tensorflow_org_customvision_1sample_env_ImageUtils_convertYUV420SPToARGB8888 and Java_demo_tensorflow_org_customvision_1sample_env_ImageUtils_convertYUV420SPToARGB8888___3B_3IIIZ)
                                                                                             at demo.tensorflow.org.customvision_sample.env.ImageUtils.convertYUV420SPToARGB8888(Native Method)
                                                                                             at demo.tensorflow.org.customvision_sample.CameraActivity.onPreviewFrame(CameraActivity.java:110)
                                                                                             at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1266)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                             at android.os.Looper.loop(Looper.java:207)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:5728)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```
I tried on different devices.

**Comment by amin-b** [comment]
@alexnik0888 Could you share your ProGuard configuration?
Are you using Android Studio 3 + Android plugin 3.0.0 (Gradle 4.1+)?

**Comment by alexnik0888** [comment]
@amin-b classpath 'com.android.tools.build:gradle:3.0.1', Android Studio 3.0.1
I didn't add any proguard rules. proguard-rules.pro is empty

**Comment by amin-b** [comment]
@alexnik0888 thanks,
what devices did you use?
one possibility is that your hardware doesn't support Camera2 api.
you can look for "Camera API lv2" in logcat, if it's showing "false" that's the reason.
 
at the moment this sample code doesn't include tensorflow_demo so library that has ImageUtils implementations. This sample is only tested/supported on Pixel phones and devices that support camera2 api.

useCamera2API flag is in CameraActivity.java.

**Comment by alexnik0888** [comment]
@amin-b thank you

**Comment by amin-b** [comment]
@alexnik0888 no problem, 
alternatively you can build the TensorFlow's [Android sample](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android) and use Custom Vision's exported model in it. 
You can use MSCognitiveServicesClassifier.java in this repo as a reference.
