### ISSUE TITLE
java.lang.IllegalArgumentException: Input to reshape is a tensor with 97556 values, but the requested shape requires a multiple of 90944

### ISSUE THREAD

**Issue by Luukjn** [Azure-Samples/cognitive-services-android-customvision-sample#22]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Load a custom classification model exported by customvision.ai into the sample application and run the application.

### Any log messages given by the failure
>
```
 I/zygote64: Do partial code cache collection, code=30KB, data=21KB
I/zygote64: After code cache collection, code=23KB, data=18KB
    Increasing code cache capacity to 128KB
E/TensorFlowInferenceInterface: Failed to run TensorFlow inference with inputs:[Placeholder], outputs:[loss]
E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: demo.tensorflow.org.customvision_sample, PID: 10651
    java.lang.IllegalArgumentException: Input to reshape is a tensor with 97556 values, but the requested shape requires a multiple of 90944
    	 [[{{node block0_0_reshape0}}]]
        at org.tensorflow.Session.run(Native Method)
        at org.tensorflow.Session.access$100(Session.java:48)
        at org.tensorflow.Session$Runner.runHelper(Session.java:314)
        at org.tensorflow.Session$Runner.run(Session.java:264)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:228)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:197)
        at org.tensorflow.contrib.android.TensorFlowInferenceInterface.run(TensorFlowInferenceInterface.java:187)
        at demo.tensorflow.org.customvision_sample.MSCognitiveServicesClassifier.classifyImage(MSCognitiveServicesClassifier.java:135)
        at demo.tensorflow.org.customvision_sample.ClassifierActivity$2.run(ClassifierActivity.java:101)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
D/tensorflow: CameraActivity: onPause demo.tensorflow.org.customvision_sample.ClassifierActivity@281ca3c

```
### Expected/desired behavior
> Classification of custom model.

### OS and Version?
> Windows 10

### Versions
> Latest commit 57cf02d  on 11 Oct 2018

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by shonohs** [comment]
Thanks for a bug report. We are looking into the issue.

**Comment by shonohs** [comment]
PR #23
