### ISSUE TITLE
VisionSkills not initialized

### ISSUE THREAD

**Issue by incognitorobito** [Azure-Samples/cognitive-services-android-customvision-sample#28]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Try to use the `inference-tensorflow-lite-libcpp-1.0.0` aar in an application and initialize the detector as shown in the samples. I am trying to setup a simple object detector based on the code from the samples. Decompiling the source and diving further it seems like there's a shared library `libVisionSkillsRuntime.so` that it is attempting to load that fails. Please advise.

```
    fun initialize() {

        CustomVisionManager.setAppContext(context.get())


        val config : CVSObjectDetector.Configuration = ObjectDetector.ConfigurationBuilder()
            .setModelFile("cvexport.manifest")
            .build()

        availableLabels = config.SupportedIdentifiers.stringVector.toList() as ArrayList<String>
        detector = ObjectDetector(config)

        isInitialized = true
    }
```

### Any log messages given by the failure
```
2020-04-05 17:29:36.072 29084-29084/fyi.meld.presto E/AndroidRuntime: FATAL EXCEPTION: main
    Process: fyi.meld.presto, PID: 29084
    java.lang.RuntimeException: Unable to start activity ComponentInfo{fyi.meld.presto/fyi.meld.presto.ui.MainActivity}: ai.customvision.visionskills.VisionSkillsException: Vision Skills not initialized
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: ai.customvision.visionskills.VisionSkillsException: Vision Skills not initialized
        at ai.customvision.visionskills.VisionSkillsManager.throwIfNotInitialized(VisionSkillsManager.java:60)
        at ai.customvision.visionskills.VisionSkillsManager.createConfiguration(VisionSkillsManager.java:65)
        at ai.customvision.visionskills.ConfigurationBase.<init>(ConfigurationBase.java:33)
        at ai.customvision.visionskills.CVSObjectDetector$Configuration.<init>(CVSObjectDetector.java:52)
        at ai.customvision.tflite.ObjectDetector$ConfigurationTensorFlowLite.<init>(ObjectDetector.java:7)
        at ai.customvision.tflite.ObjectDetector.ConfigurationBuilder(ObjectDetector.java:12)
        at fyi.meld.presto.utils.PriceEngine.initialize(PriceEngine.kt:36)
        at fyi.meld.presto.ui.MainActivity.onCreate(MainActivity.kt:65)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
```

### Expected/desired behavior
> Object detector should initialize.

### OS and Version?
> Windows 10 1909

### Versions
>Android Studio 3.6.1, Android 10 on a Pixel 3a

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by incognitorobito** [comment]
I wasn't including the aar properly.

**Comment by incognitorobito** [comment]
To help anyone else, I also needed to add the following to my app's build.gradle:

```
        ndk {
            abiFilters "armeabi-v7a", "x86", 'x86_64'
        }
```
...
```
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
```

Please update the documentation for this.

**Comment by kojiwhub** [comment]
Thank you @incognitorobito for comment.  We have updated the README about supported architecture in commit #29.
