### ISSUE TITLE
No implementation found for void demo.tensorflow.org.customvision_sample.env.ImageUtils.convertYUV420SPToARGB8888 ?

### ISSUE THREAD

**Issue by frankShih** [Azure-Samples/cognitive-services-android-customvision-sample#3]
> Please provide us with the following information:
> ---------------------------------------------------------------

### Minimal steps to reproduce
> git clone & import to android studio, then run

### Any log messages given by the failure
> /demo.tensorflow.org.customvision_sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                         Process: demo.tensorflow.org.customvision_sample, PID: 19596
                                                                                         java.lang.UnsatisfiedLinkError: No implementation found for void demo.tensorflow.org.customvision_sample.env.ImageUtils.convertYUV420SPToARGB8888(byte[], int[], int, int, boolean) (tried Java_demo_tensorflow_org_customvision_1sample_env_ImageUtils_convertYUV420SPToARGB8888 and Java_demo_tensorflow_org_customvision_1sample_env_ImageUtils_convertYUV420SPToARGB8888___3B_3IIIZ)
                                                                                             at demo.tensorflow.org.customvision_sample.env.ImageUtils.convertYUV420SPToARGB8888(Native Method)
                                                                                             at demo.tensorflow.org.customvision_sample.CameraActivity.onPreviewFrame(CameraActivity.java:110)
                                                                                             at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1208)
                                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                             at android.os.Looper.loop(Looper.java:159)
                                                                                             at android.app.ActivityThread.main(ActivityThread.java:6097)
                                                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

### OS and Version?
> Windows 10, android studio 3.0

Please give me some suggestion, thx

**Comment by amin-b** [comment]
@frankShih 
What device did you use?
possibility your hardware doesn't support Camera2 api.
you can look for "Camera API lv2" in logcat, if it's showing "false" that's the reason.

at the moment this sample code doesn't include tensorflow_demo so library. 
This sample is supported on Pixel phones and/or devices that support Camera2 api.

alternatively you can build the TensorFlow's [Android sample](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android) and use Custom Vision's exported model in it. You can use MSCognitiveServicesClassifier.java in this repo as a reference.

**Comment by WayneChien** [comment]
I have the same problem, because my phone don't support Camera2 api.
But I still not have any idea to fix this problem.
Can you answer this question in detail?

**Comment by Florin-Birgu** [comment]
[This version of the ImageUtils](https://github.com/tensorflow/tensorflow/commit/0e69f536c13d6db7e8276ee7ffe249a82d89f246
) worked for me. Probably the [latest](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/env/ImageUtils.java) would work also.

**Comment by horvathj** [comment]
@Florin-Birgu Thank You! I tried the latest and it worked!

In CameraActivity.java file I also changed this line
//      ImageUtils.convertYUV420SPToARGB8888(bytes, rgbBytes, previewWidth, previewHeight, false);
to this:
     ImageUtils.convertYUV420SPToARGB8888(bytes, previewWidth, previewHeight, rgbBytes);

**Comment by frankShih** [comment]
@amin-b 
I build the TensorFlow's Android sample and use Custom Vision's exported model in it. 
And it works! Thanks a lot!

Besides, I am wondering that if there is any way we can tune the model? 
(something like threshold, evaluation criteria etc.
For example: 
1. I want to force to classify an image to certain TAG rather than all 0's possibility
2. It seems that if the target I want to classify isn't large enough on my mobile screen (which means my camera must be really close to the target), the target can't be detected

Are there any strategies that can achieve this in CustomVision?

**Comment by amin-b** [comment]
CustomVision doesn't have a good solution today for the scenarios you mentioned.
In general if background noise (anything around your smaller target) is having big impact, training your model with many more images (with smaller target and different backgrounds) might help.
