### ISSUE TITLE
App crashes after successfully built on start up

### ISSUE THREAD

**Issue by Nephys222** [Azure-Samples/cognitive-services-android-customvision-sample#40]
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce
> Import to Android studio and built it

### Any log messages given by the failure
>
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: demo.tensorflow.org.customvision_sample, PID: 29450
    java.lang.RuntimeException: Unable to start activity ComponentInfo{demo.tensorflow.org.customvision_sample/demo.tensorflow.org.customvision_sample.ObjectDetectorActivity}: ai.customvision.visionskills.VisionSkillsException: {"NativeRuntimeError":"Skill[ObjectDetector] Build Exception <JNIWrapperException: Failed to load model; Model name = <sample-tflite.cvmodel/cvexport.manifest>; details: java.lang.IncompatibleClassChangeError: The method 'int[] org.tensorflow.lite.Tensor.shape()' was expected to be of type virtual but instead was found to be of type interface (declaration of 'ai.customvision.TensorFlowLiteWrapper' appears in /data/app/demo.tensorflow.org.customvision_sample-1/base.apk:classes2.dex)>"}
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2729)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2790)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1505)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:173)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)
     Caused by: ai.customvision.visionskills.VisionSkillsException: {"NativeRuntimeError":"Skill[ObjectDetector] Build Exception <JNIWrapperException: Failed to load model; Model name = <sample-tflite.cvmodel/cvexport.manifest>; details: java.lang.IncompatibleClassChangeError: The method 'int[] org.tensorflow.lite.Tensor.shape()' was expected to be of type virtual but instead was found to be of type interface (declaration of 'ai.customvision.TensorFlowLiteWrapper' appears in /data/app/demo.tensorflow.org.customvision_sample-1/base.apk:classes2.dex)>"}
        at ai.customvision.visionskills.VisionSkillsManager.throwIfJNIFailed(VisionSkillsManager.java:24)
        at ai.customvision.visionskills.VisionSkillsManager.SkillConfigurationBuild_orThrow(VisionSkillsManager.java:553)
        at ai.customvision.visionskills.VisionSkillsManager.skillConfigurationBuild(VisionSkillsManager.java:309)
        at ai.customvision.visionskills.ConfigurationBase.build(ConfigurationBase.java:41)
        at ai.customvision.visionskills.CVSObjectDetector$Configuration.build(CVSObjectDetector.java:66)
        at demo.tensorflow.org.customvision_sample.MSCognitiveServicesCustomVisionObjectDetector.<init>(MSCognitiveServicesCustomVisionObjectDetector.java:61)
        at demo.tensorflow.org.customvision_sample.ObjectDetectorActivity.onCreate(ObjectDetectorActivity.java:52)
        at android.app.Activity.performCreate(Activity.java:6673)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1136)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2682)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2790) 
        at android.app.ActivityThread.-wrap12(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1505) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:173) 
        at android.app.ActivityThread.main(ActivityThread.java:6523) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:938) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:828)

### Expected/desired behavior
> Start the app on the phone

### OS and Version?
> Windows 10. 

### Versions
> Android Studio Arctic Fox 2020.3.1 Patch 3

**Comment by natheemy** [comment]
Downgrade tensorflow library :) 

   implementation 'org.tensorflow:tensorflow-lite:2.5.0'

**Comment by Nephys222** [comment]
Thanks @Cyberstag. It worked.
