### ISSUE TITLE
I tried the application in Emulator and Installed in Phone. Both it crashes once up.

### ISSUE THREAD

**Issue by vairaselvam** [Azure-Samples/cognitive-services-android-customvision-sample#7]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>

### Any log messages given by the failure
>

### Expected/desired behavior
>

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)

### Versions
>

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by amin-b** [comment]
@vairaselvam please provide logs to be able to narrow down the issue.
Does your phone support Camera2 API?

**Comment by vairaselvam** [comment]
Please find the comments below during my run in Emulator. I am using Samsung and Lenovo phone which are latest but not sure they supports Camera2 API. I am new to Android development. My suggestion is the provide a solution which works with commonly using phones instead of only Camera2 Api  (which is hard to find).

Thanks and sorry if I am anything wrong !!!


****03-01 17:21:07.046 2838-2838/? I/art: Not late-enabling -Xcheck:jni (already on)
03-01 17:21:07.413 2838-2838/demo.tensorflow.org.customvision_sample I/InstantRun: starting instant run server: is main process
03-01 17:21:07.625 2838-2838/demo.tensorflow.org.customvision_sample D/tensorflow: CameraActivity: onCreate demo.tensorflow.org.customvision_sample.ClassifierActivity@2073868e
03-01 17:21:07.740 2838-2838/demo.tensorflow.org.customvision_sample I/CameraManagerGlobal: getCameraService: Reconnecting to camera service
03-01 17:21:07.768 2838-2850/demo.tensorflow.org.customvision_sample W/art: Suspending all threads took: 5.320ms
03-01 17:21:07.839 2838-2850/demo.tensorflow.org.customvision_sample I/art: Background sticky concurrent mark sweep GC freed 3209(274KB) AllocSpace objects, 0(0B) LOS objects, 39% free, 367KB/605KB, paused 7.816ms total 139.075ms
03-01 17:21:08.000 2838-2838/demo.tensorflow.org.customvision_sample D/tensorflow: CameraActivity: onStart demo.tensorflow.org.customvision_sample.ClassifierActivity@2073868e
03-01 17:21:08.000 2838-2838/demo.tensorflow.org.customvision_sample D/tensorflow: CameraActivity: onResume demo.tensorflow.org.customvision_sample.ClassifierActivity@2073868e
03-01 17:21:08.009 2838-2856/demo.tensorflow.org.customvision_sample D/OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
                                                                                       
                                                                                       [ 03-01 17:21:08.013  2838: 2838 D/         ]
                                                                                       HostConnection::get() New Host Connection established 0xa584a150, tid 2838
03-01 17:21:08.014 2838-2838/demo.tensorflow.org.customvision_sample D/Atlas: Validating map...
03-01 17:21:08.066 2838-2856/demo.tensorflow.org.customvision_sample I/OpenGLRenderer: Initialized EGL, version 1.4
03-01 17:21:08.066 2838-2856/demo.tensorflow.org.customvision_sample W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
03-01 17:21:08.096 2838-2856/demo.tensorflow.org.customvision_sample D/OpenGLRenderer: Enabling debug mode 0
03-01 17:21:08.204 2838-2838/demo.tensorflow.org.customvision_sample W/CameraBase: An error occurred while connecting to camera: -1
03-01 17:21:08.205 2838-2838/demo.tensorflow.org.customvision_sample D/AndroidRuntime: Shutting down VM
03-01 17:21:08.215 2838-2838/demo.tensorflow.org.customvision_sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                       Process: demo.tensorflow.org.customvision_sample, PID: 2838
                                                                                       java.lang.RuntimeException: Fail to connect to camera service
                                                                                           at android.hardware.Camera.<init>(Camera.java:497)
                                                                                           at android.hardware.Camera.open(Camera.java:342)
                                                                                           at demo.tensorflow.org.customvision_sample.LegacyCameraConnectionFragment$1.onSurfaceTextureAvailable(LegacyCameraConnectionFragment.java:79)
                                                                                           at android.view.TextureView.getHardwareLayer(TextureView.java:370)
                                                                                           at android.view.View.updateDisplayListIfDirty(View.java:14144)
                                                                                           at android.view.View.getDisplayList(View.java:14189)
                                                                                           at android.view.View.draw(View.java:14959)
                                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                                                           at android.view.View.updateDisplayListIfDirty(View.java:14162)
                                                                                           at android.view.View.getDisplayList(View.java:14189)
                                                                                           at android.view.View.draw(View.java:14959)
                                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                                                           at android.view.View.draw(View.java:15234)
                                                                                           at android.widget.FrameLayout.draw(FrameLayout.java:598)
                                                                                           at android.view.View.updateDisplayListIfDirty(View.java:14167)
                                                                                           at android.view.View.getDisplayList(View.java:14189)
                                                                                           at android.view.View.draw(View.java:14959)
                                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                                                           at android.view.View.updateDisplayListIfDirty(View.java:14162)
                                                                                           at android.view.View.getDisplayList(View.java:14189)
                                                                                           at android.view.View.draw(View.java:14959)
                                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                                                           at android.view.View.updateDisplayListIfDirty(View.java:14162)
                                                                                           at android.view.View.getDisplayList(View.java:14189)
                                                                                           at android.view.View.draw(View.java:14959)
                                                                                           at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                                                           at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                                                           at android.view.View.draw(View.java:15234)
                                                                                           at android.widget.FrameLayout.draw(FrameLayout.java:598)
                                                                                           at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2650)
                                                                                           at android.view.View.updateDisplayListIfDirty(View.java:14167)
                                                                                           at android.view.View.getDisplayList(View.java:14189)
                                                                                           at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:273)
                                                                                           at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:279)
                                                                                           at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:318)
                                                                                           at android.view.ViewRootImpl.draw(ViewRootImpl.java:2530)
                                                                                           at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
                                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
                                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
                                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
                                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                                           at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:5257)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
03-01 17:21:11.214 2838-2838/demo.tensorflow.org.customvision_sample I/Process: Sending signal. PID: 2838 SIG**: 9**

**Comment by amin-b** [comment]
Thanks for you feedback, we will look into that.

About your issue/crashes, you need to run this sample one a device, it won't work on emulator.
regarding whether or not your device supports camera2 apis, when you run the app lookup "Camera API lv2" in logcat, if it's showing "false" then that means you device doesn't support it.

Camera apis are [deprecated](https://developer.android.com/reference/android/hardware/Camera.html) in API level 21 and it's suggested to move to Camera2. 

If you have to use Camera apis you can use TensorFlow's latest Android sample. 
Please go through open/resolved issues before opening a new issue, you can find the solution to your problem and how others managed to use Camera api there.
